# Generated by Django 4.2.13 on 2024-05-24 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crops', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='crophistory',
            options={'verbose_name': 'Crop History', 'verbose_name_plural': 'Crop Histories'},
        ),
        migrations.AlterField(
            model_name='crophistory',
            name='predication',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
