# Generated by Django 4.2.13 on 2024-05-24 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crops', '0002_alter_crophistory_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crophistory',
            name='predication',
            field=models.CharField(blank=True, max_length=360, null=True),
        ),
    ]
